name: Deploy WAR to Tomcat

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy WAR to Tomcat
      run: |
        curl -v --upload-file deployment/MyProject.war "http://192.168.1.100:8080/MyProject" \
          --user admin:admin
